syntax = "proto3";
option csharp_namespace = "Graph";
package graph;

service GraphGrpc {
  rpc GetNodes (Empty) returns (NodeList);
  rpc AddNode (AddNodeRequest) returns (AddNodeResponse);
  rpc DeleteNode (DeleteNodeRequest) returns (DeleteNodeResponse);
  rpc GetEdges (Empty) returns (EdgeList);
  rpc AddEdge (AddEdgeRequest) returns (AddEdgeResponse);
  rpc DeleteEdge (DeleteEdgeRequest) returns (DeleteEdgeResponse);
  rpc GenerateNodes (GenerateNodesRequest) returns (GenerateNodesResponse);
}

message Empty {}

message NodeModel{
  int32 id = 1;
  string name = 2;
  double in_value = 3;
  double out_value = 4;
  NodeType type = 5;
}

enum NodeType {
  CONSUMER = 0;
  SOURCE = 1;
  TRANSITIVE = 2;
}

message NodeList {
  repeated NodeModel nodes = 1;
}

message AddNodeRequest {
  NodeModel node = 1;
}

message AddNodeResponse {
  string message = 1;
  int32 id = 2;
}

message DeleteNodeRequest {
  int32 id = 1;
}

message DeleteNodeResponse {
  string message = 1;
}

message EdgeModel {
  int32 id = 1;
  int32 source_id = 2;
  int32 target_id = 3;
  double weight = 4;
}

message EdgeList {
  repeated EdgeModel edges = 1;
}

message AddEdgeRequest {
  EdgeModel edge = 1;
}

message AddEdgeResponse {
  string message = 1;
  int32 id = 2;
}

message DeleteEdgeRequest {
  int32 id = 1;
}

message DeleteEdgeResponse {
  string message = 1;
}

message GenerateNodesRequest {
  int32 count = 1;
}

message GenerateNodesResponse {
  string message = 1;
  int32 total_nodes = 2;
}