<Project Sdk="Aspire.AppHost.Sdk/13.2.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>7b28175e-3808-4bad-84f1-66bf36bd59a7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Generator_Service26.Server\Generator_Service26.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.2.4" />
  </ItemGroup>
</Project>
